# -*- coding: utf-8 -*-
"""python Day 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MP7w2TEaHqZrnzgOOXtGgAYf6hDzz-Cu
"""

print("dilip")

print ("hello
world")

print ("hello \
world")

print (""___________                        _________                      __  .__    .__                 
\__    ___/__.__.______   ____    /   _____/ ____   _____   _____/  |_|  |__ |__| ____    ____   
  |    | <   |  |\____ \_/ __ \   \_____  \ /  _ \ /     \_/ __ \   __\  |  \|  |/    \  / ___\  
  |    |  \___  ||  |_> >  ___/   /        (  <_> )  Y Y  \  ___/|  | |   Y  \  |   |  \/ /_/  > 
  |____|  / ____||   __/ \___  > /_______  /\____/|__|_|  /\___  >__| |___|  /__|___|  /\___  /  
          \/     |__|        \/          \/             \/     \/          \/        \//_____/   "")

print ("""___________                        _________                      __  .__    .__                 
\__    ___/__.__.______   ____    /   _____/ ____   _____   _____/  |_|  |__ |__| ____    ____   
  |    | <   |  |\____ \_/ __ \   \_____  \ /  _ \ /     \_/ __ \   __\  |  \|  |/    \  / ___\  
  |    |  \___  ||  |_> >  ___/   /        (  <_> )  Y Y  \  ___/|  | |   Y  \  |   |  \/ /_/  > 
  |____|  / ____||   __/ \___  > /_______  /\____/|__|_|  /\___  >__| |___|  /__|___|  /\___  /  
          \/     |__|        \/          \/             \/     \/          \/        \//_____/   """)

print ('python's world')

print ('python world')

print ("python's world")

print ("hello\tpython")

print ("hello\npython")

print ('python\'s world')

print ("hello\a")

name = "dj"
marks = "100"
age = "15"
print ("the name of the person is",name,"marks is",marks,"age is",age)

name = "dj"
marks = 35.75
age = 16
print ("the name of the person is",name,"marks is",marks,"age is",age)

print ("the name of person is %s marks is %f age is %d"%(name,marks,age))

print ("the name of person is %10s marks is %10f age is %10d"%(name,marks,age))

print ("the name of person is %10s marks is %10.2f age is %10d"%(name,marks,age))

print (f"the name of person is {name} the marks is {marks} age is {age}")

print (f"the name of person is {name} the marks is {35.75} age is {age}")

"""### **Arithmetic operators**"""

5**5

10+20

10-20

10/2

10%3

10/3

10//3

"""### **Comparsion operators**"""

a=10
b=20
a==b

c=10
a==c

c < a

c <=a

a >=b

a!=b

"""### **Assignment operators**"""

a=10
print (a)

a=10
b=10
a=a+b
print(a)

a=10
b=10
a=a-b
print(a)

"""### **Bitwise operators**"""

a=240
b=1
a|b

a&b

"""### **Logical operator**"""

a=1
b=20
a > 20

a>20 or 10>9

a>20 and 10>9

10>9 and 20>m

10<9 and 20>m

not 10<9

not True

"""### **Membership operator**"""

str1="pythonprogrammming"
"a" in str1

str1="programming"
"x"in str1

str1="programming"
"x"not in str1

x="dj"
"d"in x

"""### **Identity operators**"""

a=10
b=10
a == b

a is b

id (a)

id(b)

x=1.5
y=1.5
x==y

x is y

id(x)

id(y)

a=257
b=257
a==b

a is b

a=256
b=256
a==b

a is b

a=-1
b=-1
a==b

a is b

a=-5
b=-5
a==b

a is b

"""### **Operator precedence**"""

10+10/29*4

2**-1

a=-6
b=-6
a==b

a is b

10>8>9